#-------------------------------------------------
#
# Project created by QtCreator 2023-11-05T23:48:59
#
#-------------------------------------------------

QT       += core gui
QT       += network
QT       +=opengl
QT       +=widgets
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

LIBS     += -lglut -lGLU
TARGET = IIMT-CR
TEMPLATE = app
QT       += serialport

# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
# DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
        main.cpp \
        widget.cpp \
    Robort_Data_Ready_Thread/trajectoryplanthread.cpp \
    Robort_Data_Send_Thread/robotthread.cpp \
    Global_Function/GlobalFunction.cpp \
    Global_Function/global_paramodel.cpp \
    Trajectory_JLP/trajectory.cpp \
    Pci_Can/pci_thread.cpp \
    Pci_Can/pci_send_thread.cpp \
    Motor_Model/motor_model.cpp \
    query_manager/query_manager.cpp \
    query_manager/query_item.cpp \
    query_manager/link_list.cpp \
    Global_Function/global_varable.cpp \
    Global_Function/global_model_define.cpp \
    Global_Function/global_paramode_define.cpp \
    Motor_Model/motor_modelfunction.cpp \
    Pci_Can/pci_information_defination.cpp \
    Pci_Can/pcan_control.cpp \
    Pci_Can/pci_defuncitions.cpp \
    Motor_Model/motor_varable.cpp \
    Tree_struct/tree_struct_model.cpp \
    Program_UI/set_ui/c_setting.cpp \
    Program_UI/robort_tree_ui/c_treerobortstruct.cpp \
    Program_UI/robort_move_ui/robort_move.cpp \
    Link_File/copley.c \
    Link_File/doublylinkedlist.c \
    Trajectory_JLP/cycle_traj_planing.cpp \
    Trajectory_JLP/jog_traj_planing.cpp \
    Trajectory_JLP/line_traj_planing.cpp \
    Trajectory_JLP/pvt_speed_planing.cpp \
    Trajectory_JLP/time_traj.cpp \
    Link_File/kine_tran.cpp \
    Link_File/ur_kin.cpp \
    Link_File/kinematic.c \
    Program_UI/robort_tree_ui/move_widget.cpp \
    Program_UI/robort_tree_ui/waypoint.cpp \
    Program_UI/robort_tree_ui/setio.cpp \
    Program_UI/robort_tree_ui/waitset.cpp \
    Link_File/judge_singular_point.cpp \
    Link_File/robotfunctions.cpp \
    Link_File/robottransform.cpp \
    Link_File/step_descartes.cpp \
    Link_File/rotate_world_base.cpp \
    Link_File/tcp_app.cpp \
    Link_File/tcp_kinematic.cpp \
    Program_UI/set_ui/paramwidget.cpp \
    Io_Communication/485/serialport.cpp \
    Io_Communication/io/io.cpp \
    Pci_Can/pcan_init.cpp \
    Program_UI/robort_tree_ui/code_intrupt.cpp \
    Code_Interupt_File/InterpFile_read.cpp \
    Code_Interupt_File/interp_handle.cpp \
    Code_Interupt_File/interp_varible.cpp \
    Code_Interupt_File/interup_thread.cpp \
    Program_UI/robort_tree_ui/tree_stack.cpp \
    Program_UI/robort_tree_ui/tree_stack_varible.cpp \
    Program_UI/robort_tree_ui/treestackfunction.cpp \
    Program_UI/fix_ui/fix.cpp \
    Program_UI/KeyBoard_ui/keyboardnumdialog.cpp \
    Program_UI/KeyBoard_ui/keyboard.cpp \
    Program_UI/fix_ui/lineeditinput.cpp \
    Program_UI/fix_ui/fix_varible.cpp \
    Program_UI/fix_ui/TCP/tcp_calibration.cpp \
    Program_UI/set_ui/Dh_param_varible.cpp \
    Dynamic_Programing/Do_Current_Detection/detectcollison.cpp \
    Dynamic_Programing/Do_Current_Detection/do_deal_current.cpp \
    Dynamic_Programing/Do_Current_Detection/qmessagboxdefine.cpp \
    Dynamic_Programing/Dynamic_Project/Collision_Judge.cpp \
    Dynamic_Programing/Dynamic_Project/Kinematics.cpp \
    Dynamic_Programing/Dynamic_Project/Newton_Euler.cpp \
    Dynamic_Programing/Dynamic_Project/Para_List.cpp \
    Dynamic_Programing/Dynamic_Project/Tao_Friction.cpp \
    Dynamic_Programing/Dynamic_Project/test.cpp \
    Dynamic_Programing/Dynamic_Project/Torque_Force.cpp \
    Dynamic_Programing/dynaic_forward.cpp \
    NetWork/utils.cpp \
    NetWork/NetworkServer.cpp \
    NetWork/MoveService.cpp \
    NetWork/iimtData.cpp \
    Upper_Conect/traj_plan_base.cpp \
    Opengl_robot/model.cpp \
    Opengl_robot/model.cpp \
    Opengl_robot/scara.cpp \
    Opengl_robot/glwidget.cpp

HEADERS += \
        widget.h \
    Robort_Data_Ready_Thread/trajectoryplanthread.h \
    Robort_Data_Send_Thread/robotthread.h \
    Global_Function/GlobalFunction.h \
    Global_Function/global_paramodel.h \
    Trajectory_JLP/trajectory.h \
    Pci_Can/pci_thread.h \
    Pci_Can/pci_send_thread.h \
    Motor_Model/motor_model.h \
    query_manager/query_manager.h \
    query_manager/query_item.h \
    query_manager/link_list.h \
    Global_Function/global_varable.h \
    Global_Function/global_model_define.h \
    Global_Function/global_paramode_define.h \
    Motor_Model/motor_modelfunction.h \
    Pci_Can/pci_information.h \
    Pci_Can/pci_information_defination.h \
    Pci_Can/pcan_control.h \
    Pci_Can/pci_defuncitions.h \
    Motor_Model/motor_varable.h \
    Tree_struct/tree_struct_model.h \
    Program_UI/set_ui/c_setting.h \
    Program_UI/robort_tree_ui/c_treerobortstruct.h \
    Program_UI/robort_move_ui/robort_move.h \
    Link_File/copley.h \
    Link_File/doublylinkedlist.h \
    Trajectory_JLP/cycle_traj_planing.h \
    Trajectory_JLP/jog_traj_planing.h \
    Trajectory_JLP/line_traj_paning.h \
    Trajectory_JLP/pvt_speed_planing.h \
    Trajectory_JLP/time_traj.h \
    Eigen/Cholesky \
    Eigen/CholmodSupport \
    Eigen/Core \
    Eigen/Dense \
    Eigen/Eigen \
    Eigen/Eigenvalues \
    Eigen/Geometry \
    Eigen/Householder \
    Eigen/IterativeLinearSolvers \
    Eigen/Jacobi \
    Eigen/LU \
    Eigen/MetisSupport \
    Eigen/OrderingMethods \
    Eigen/PardisoSupport \
    Eigen/PaStiXSupport \
    Eigen/QR \
    Eigen/QtAlignedMalloc \
    Eigen/Sparse \
    Eigen/SparseCholesky \
    Eigen/SparseCore \
    Eigen/SparseLU \
    Eigen/SparseQR \
    Eigen/SPQRSupport \
    Eigen/StdDeque \
    Eigen/StdList \
    Eigen/StdVector \
    Eigen/SuperLUSupport \
    Eigen/SVD \
    Eigen/UmfPackSupport \
    Eigen/src/Cholesky/LDLT.h \
    Eigen/src/Cholesky/LLT.h \
    Eigen/src/Cholesky/LLT_LAPACKE.h \
    Eigen/src/CholmodSupport/CholmodSupport.h \
    Eigen/src/Cholesky/LDLT.h \
    Eigen/src/Cholesky/LLT.h \
    Eigen/src/Cholesky/LLT_LAPACKE.h \
    Eigen/src/CholmodSupport/CholmodSupport.h \
    Eigen/src/Core/arch/AltiVec/Complex.h \
    Eigen/src/Core/arch/AltiVec/MathFunctions.h \
    Eigen/src/Core/arch/AltiVec/PacketMath.h \
    Eigen/src/Core/arch/AVX/Complex.h \
    Eigen/src/Core/arch/AVX/MathFunctions.h \
    Eigen/src/Core/arch/AVX/PacketMath.h \
    Eigen/src/Core/arch/AVX/TypeCasting.h \
    Eigen/src/Core/arch/AVX512/MathFunctions.h \
    Eigen/src/Core/arch/AVX512/PacketMath.h \
    Eigen/src/Core/arch/CUDA/Complex.h \
    Eigen/src/Core/arch/CUDA/Half.h \
    Eigen/src/Core/arch/CUDA/MathFunctions.h \
    Eigen/src/Core/arch/CUDA/PacketMath.h \
    Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
    Eigen/src/Core/arch/CUDA/TypeCasting.h \
    Eigen/src/Core/arch/Default/Settings.h \
    Eigen/src/Core/arch/NEON/Complex.h \
    Eigen/src/Core/arch/NEON/MathFunctions.h \
    Eigen/src/Core/arch/NEON/PacketMath.h \
    Eigen/src/Core/arch/SSE/Complex.h \
    Eigen/src/Core/arch/SSE/MathFunctions.h \
    Eigen/src/Core/arch/SSE/PacketMath.h \
    Eigen/src/Core/arch/SSE/TypeCasting.h \
    Eigen/src/Core/arch/ZVector/Complex.h \
    Eigen/src/Core/arch/ZVector/MathFunctions.h \
    Eigen/src/Core/arch/ZVector/PacketMath.h \
    Eigen/src/Core/functors/AssignmentFunctors.h \
    Eigen/src/Core/functors/BinaryFunctors.h \
    Eigen/src/Core/functors/NullaryFunctors.h \
    Eigen/src/Core/functors/StlFunctors.h \
    Eigen/src/Core/functors/TernaryFunctors.h \
    Eigen/src/Core/functors/UnaryFunctors.h \
    Eigen/src/Core/products/GeneralBlockPanelKernel.h \
    Eigen/src/Core/products/GeneralMatrixMatrix.h \
    Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
    Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
    Eigen/src/Core/products/GeneralMatrixVector.h \
    Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
    Eigen/src/Core/products/Parallelizer.h \
    Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
    Eigen/src/Core/products/SelfadjointMatrixVector.h \
    Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
    Eigen/src/Core/products/SelfadjointProduct.h \
    Eigen/src/Core/products/SelfadjointRank2Update.h \
    Eigen/src/Core/products/TriangularMatrixMatrix.h \
    Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
    Eigen/src/Core/products/TriangularMatrixVector.h \
    Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
    Eigen/src/Core/products/TriangularSolverMatrix.h \
    Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
    Eigen/src/Core/products/TriangularSolverVector.h \
    Eigen/src/Core/util/BlasUtil.h \
    Eigen/src/Core/util/Constants.h \
    Eigen/src/Core/util/DisableStupidWarnings.h \
    Eigen/src/Core/util/ForwardDeclarations.h \
    Eigen/src/Core/util/Macros.h \
    Eigen/src/Core/util/Memory.h \
    Eigen/src/Core/util/Meta.h \
    Eigen/src/Core/util/MKL_support.h \
    Eigen/src/Core/util/NonMPL2.h \
    Eigen/src/Core/util/ReenableStupidWarnings.h \
    Eigen/src/Core/util/StaticAssert.h \
    Eigen/src/Core/util/XprHelper.h \
    Eigen/src/Core/Array.h \
    Eigen/src/Core/ArrayBase.h \
    Eigen/src/Core/ArrayWrapper.h \
    Eigen/src/Core/Assign.h \
    Eigen/src/Core/Assign_MKL.h \
    Eigen/src/Core/AssignEvaluator.h \
    Eigen/src/Core/BandMatrix.h \
    Eigen/src/Core/Block.h \
    Eigen/src/Core/BooleanRedux.h \
    Eigen/src/Core/CommaInitializer.h \
    Eigen/src/Core/ConditionEstimator.h \
    Eigen/src/Core/CoreEvaluators.h \
    Eigen/src/Core/CoreIterators.h \
    Eigen/src/Core/CwiseBinaryOp.h \
    Eigen/src/Core/CwiseNullaryOp.h \
    Eigen/src/Core/CwiseTernaryOp.h \
    Eigen/src/Core/CwiseUnaryOp.h \
    Eigen/src/Core/CwiseUnaryView.h \
    Eigen/src/Core/DenseBase.h \
    Eigen/src/Core/DenseCoeffsBase.h \
    Eigen/src/Core/DenseStorage.h \
    Eigen/src/Core/Diagonal.h \
    Eigen/src/Core/DiagonalMatrix.h \
    Eigen/src/Core/DiagonalProduct.h \
    Eigen/src/Core/Dot.h \
    Eigen/src/Core/EigenBase.h \
    Eigen/src/Core/ForceAlignedAccess.h \
    Eigen/src/Core/Fuzzy.h \
    Eigen/src/Core/GeneralProduct.h \
    Eigen/src/Core/GenericPacketMath.h \
    Eigen/src/Core/GlobalFunctions.h \
    Eigen/src/Core/Inverse.h \
    Eigen/src/Core/IO.h \
    Eigen/src/Core/Map.h \
    Eigen/src/Core/MapBase.h \
    Eigen/src/Core/MathFunctions.h \
    Eigen/src/Core/MathFunctionsImpl.h \
    Eigen/src/Core/Matrix.h \
    Eigen/src/Core/MatrixBase.h \
    Eigen/src/Core/NestByValue.h \
    Eigen/src/Core/NoAlias.h \
    Eigen/src/Core/NumTraits.h \
    Eigen/src/Core/PermutationMatrix.h \
    Eigen/src/Core/PlainObjectBase.h \
    Eigen/src/Core/Product.h \
    Eigen/src/Core/ProductEvaluators.h \
    Eigen/src/Core/Random.h \
    Eigen/src/Core/Redux.h \
    Eigen/src/Core/Ref.h \
    Eigen/src/Core/Replicate.h \
    Eigen/src/Core/ReturnByValue.h \
    Eigen/src/Core/Reverse.h \
    Eigen/src/Core/Select.h \
    Eigen/src/Core/SelfAdjointView.h \
    Eigen/src/Core/SelfCwiseBinaryOp.h \
    Eigen/src/Core/Solve.h \
    Eigen/src/Core/SolverBase.h \
    Eigen/src/Core/SolveTriangular.h \
    Eigen/src/Core/StableNorm.h \
    Eigen/src/Core/Stride.h \
    Eigen/src/Core/Swap.h \
    Eigen/src/Core/Transpose.h \
    Eigen/src/Core/Transpositions.h \
    Eigen/src/Core/TriangularMatrix.h \
    Eigen/src/Core/VectorBlock.h \
    Eigen/src/Core/VectorwiseOp.h \
    Eigen/src/Core/Visitor.h \
    Eigen/src/Eigenvalues/ComplexEigenSolver.h \
    Eigen/src/Eigenvalues/ComplexSchur.h \
    Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
    Eigen/src/Eigenvalues/EigenSolver.h \
    Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
    Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    Eigen/src/Eigenvalues/HessenbergDecomposition.h \
    Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    Eigen/src/Eigenvalues/RealQZ.h \
    Eigen/src/Eigenvalues/RealSchur.h \
    Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
    Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
    Eigen/src/Eigenvalues/Tridiagonalization.h \
    Eigen/src/Geometry/arch/Geometry_SSE.h \
    Eigen/src/Geometry/AlignedBox.h \
    Eigen/src/Geometry/AngleAxis.h \
    Eigen/src/Geometry/EulerAngles.h \
    Eigen/src/Geometry/Homogeneous.h \
    Eigen/src/Geometry/Hyperplane.h \
    Eigen/src/Geometry/OrthoMethods.h \
    Eigen/src/Geometry/ParametrizedLine.h \
    Eigen/src/Geometry/Quaternion.h \
    Eigen/src/Geometry/Rotation2D.h \
    Eigen/src/Geometry/RotationBase.h \
    Eigen/src/Geometry/Scaling.h \
    Eigen/src/Geometry/Transform.h \
    Eigen/src/Geometry/Translation.h \
    Eigen/src/Geometry/Umeyama.h \
    Eigen/src/Householder/BlockHouseholder.h \
    Eigen/src/Householder/Householder.h \
    Eigen/src/Householder/HouseholderSequence.h \
    Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
    Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
    Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
    Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
    Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
    Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
    Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
    Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
    Eigen/src/Jacobi/Jacobi.h \
    Eigen/src/LU/arch/Inverse_SSE.h \
    Eigen/src/LU/Determinant.h \
    Eigen/src/LU/FullPivLU.h \
    Eigen/src/LU/InverseImpl.h \
    Eigen/src/LU/PartialPivLU.h \
    Eigen/src/LU/PartialPivLU_LAPACKE.h \
    Eigen/src/MetisSupport/MetisSupport.h \
    Eigen/src/misc/blas.h \
    Eigen/src/misc/Image.h \
    Eigen/src/misc/Kernel.h \
    Eigen/src/misc/lapack.h \
    Eigen/src/misc/lapacke.h \
    Eigen/src/misc/lapacke_mangling.h \
    Eigen/src/misc/RealSvd2x2.h \
    Eigen/src/OrderingMethods/Amd.h \
    Eigen/src/OrderingMethods/Eigen_Colamd.h \
    Eigen/src/OrderingMethods/Ordering.h \
    Eigen/src/PardisoSupport/PardisoSupport.h \
    Eigen/src/PaStiXSupport/PaStiXSupport.h \
    Eigen/src/plugins/ArrayCwiseBinaryOps.h \
    Eigen/src/plugins/ArrayCwiseUnaryOps.h \
    Eigen/src/plugins/BlockMethods.h \
    Eigen/src/plugins/CommonCwiseBinaryOps.h \
    Eigen/src/plugins/CommonCwiseUnaryOps.h \
    Eigen/src/plugins/MatrixCwiseBinaryOps.h \
    Eigen/src/plugins/MatrixCwiseUnaryOps.h \
    Eigen/src/QR/ColPivHouseholderQR.h \
    Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
    Eigen/src/QR/CompleteOrthogonalDecomposition.h \
    Eigen/src/QR/FullPivHouseholderQR.h \
    Eigen/src/QR/HouseholderQR.h \
    Eigen/src/QR/HouseholderQR_LAPACKE.h \
    Eigen/src/SparseCholesky/SimplicialCholesky.h \
    Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
    Eigen/src/SparseCore/AmbiVector.h \
    Eigen/src/SparseCore/CompressedStorage.h \
    Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
    Eigen/src/SparseCore/MappedSparseMatrix.h \
    Eigen/src/SparseCore/SparseAssign.h \
    Eigen/src/SparseCore/SparseBlock.h \
    Eigen/src/SparseCore/SparseColEtree.h \
    Eigen/src/SparseCore/SparseCompressedBase.h \
    Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
    Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
    Eigen/src/SparseCore/SparseDenseProduct.h \
    Eigen/src/SparseCore/SparseDiagonalProduct.h \
    Eigen/src/SparseCore/SparseDot.h \
    Eigen/src/SparseCore/SparseFuzzy.h \
    Eigen/src/SparseCore/SparseMap.h \
    Eigen/src/SparseCore/SparseMatrix.h \
    Eigen/src/SparseCore/SparseMatrixBase.h \
    Eigen/src/SparseCore/SparsePermutation.h \
    Eigen/src/SparseCore/SparseProduct.h \
    Eigen/src/SparseCore/SparseRedux.h \
    Eigen/src/SparseCore/SparseRef.h \
    Eigen/src/SparseCore/SparseSelfAdjointView.h \
    Eigen/src/SparseCore/SparseSolverBase.h \
    Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
    Eigen/src/SparseCore/SparseTranspose.h \
    Eigen/src/SparseCore/SparseTriangularView.h \
    Eigen/src/SparseCore/SparseUtil.h \
    Eigen/src/SparseCore/SparseVector.h \
    Eigen/src/SparseCore/SparseView.h \
    Eigen/src/SparseCore/TriangularSolver.h \
    Eigen/src/SparseLU/SparseLU.h \
    Eigen/src/SparseLU/SparseLU_column_bmod.h \
    Eigen/src/SparseLU/SparseLU_column_dfs.h \
    Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
    Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
    Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
    Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
    Eigen/src/SparseLU/SparseLU_Memory.h \
    Eigen/src/SparseLU/SparseLU_panel_bmod.h \
    Eigen/src/SparseLU/SparseLU_panel_dfs.h \
    Eigen/src/SparseLU/SparseLU_pivotL.h \
    Eigen/src/SparseLU/SparseLU_pruneL.h \
    Eigen/src/SparseLU/SparseLU_relax_snode.h \
    Eigen/src/SparseLU/SparseLU_Structs.h \
    Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
    Eigen/src/SparseLU/SparseLU_Utils.h \
    Eigen/src/SparseLU/SparseLUImpl.h \
    Eigen/src/SparseQR/SparseQR.h \
    Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
    Eigen/src/StlSupport/details.h \
    Eigen/src/StlSupport/StdDeque.h \
    Eigen/src/StlSupport/StdList.h \
    Eigen/src/StlSupport/StdVector.h \
    Eigen/src/SuperLUSupport/SuperLUSupport.h \
    Eigen/src/SVD/BDCSVD.h \
    Eigen/src/SVD/JacobiSVD.h \
    Eigen/src/SVD/JacobiSVD_LAPACKE.h \
    Eigen/src/SVD/SVDBase.h \
    Eigen/src/SVD/UpperBidiagonalization.h \
    Eigen/src/UmfPackSupport/UmfPackSupport.h \
    Link_File/kinematic.h \
    Link_File/kine_tran.h \
    Link_File/ur_kin.h \
    Program_UI/robort_tree_ui/move_widget.h \
    Program_UI/robort_tree_ui/waypoint.h \
    Program_UI/robort_tree_ui/setio.h \
    Program_UI/robort_tree_ui/waitset.h \
    Link_File/judge_singular_point.h \
    Link_File/robotfunctions.h \
    Link_File/robottransform.h \
    Link_File/step_descartes.h \
    Link_File/rotate_world_base.h \
    Link_File/tcp_app.h \
    Link_File/tcp_kinematic.h \
    Program_UI/set_ui/paramwidget.h \
    Robort_Data_Ready_Thread/trajectory_model_defuction_copy.h \
    Io_Communication/485/serialport.h \
    Io_Communication/io/io.h \
    Io_Communication/io/io_interface.h \
    Pci_Can/pcan_init.h \
    Program_UI/robort_tree_ui/code_intrupt.h \
    Code_Interupt_File/interp_handle.h \
    Code_Interupt_File/interp_varible.h \
    Code_Interupt_File/interp_struct.h \
    Code_Interupt_File/interup_words.h \
    Code_Interupt_File/interp_varible.h \
    Code_Interupt_File/de_interupvaroble.h \
    Code_Interupt_File/interup_thread.h \
    Program_UI/robort_tree_ui/tree_stack.h \
    Program_UI/robort_tree_ui/tree_stack_varible.h \
    Program_UI/robort_tree_ui/treestackfunction.h \
    Program_UI/fix_ui/fix.h \
    Program_UI/KeyBoard_ui/keyboardnumdialog.h \
    Program_UI/KeyBoard_ui/keyboard.h \
    Program_UI/fix_ui/lineeditinput.h \
    Program_UI/fix_ui/fix_varible.h \
    Program_UI/fix_ui/TCP/tcp_calibration.h \
    Program_UI/set_ui/Dh_param_varible.h \
    Dynamic_Programing/Do_Current_Detection/detectcollison.h \
    Dynamic_Programing/Do_Current_Detection/do_deal_current.h \
    Dynamic_Programing/Do_Current_Detection/qmessagboxdefine.h \
    Dynamic_Programing/Dynamic_Project/Collision_Judge.h \
    Dynamic_Programing/Dynamic_Project/Collision_Para.h \
    Dynamic_Programing/Dynamic_Project/Kinematics.h \
    Dynamic_Programing/Dynamic_Project/Newton_Euler.h \
    Dynamic_Programing/Dynamic_Project/Para_List.h \
    Dynamic_Programing/Dynamic_Project/Tao_Friction.h \
    Dynamic_Programing/Dynamic_Project/test.h \
    Dynamic_Programing/Dynamic_Project/Torque_Force.h \
    Dynamic_Programing/dynaic_forward.h \
    NetWork/utils.h \
    NetWork/NetworkServer.h \
    NetWork/MoveService.h \
    NetWork/iimtData.h \
    Upper_Conect/traj_plan_base.h \
    Opengl_robot/model.h \
    Opengl_robot/scara.h \
    Opengl_robot/glwidget.h

FORMS += \
        widget.ui \
    Program_UI/set_ui/c_setting.ui \
    Program_UI/robort_tree_ui/c_treerobortstruct.ui \
    Program_UI/robort_move_ui/robort_move.ui \
    Program_UI/robort_tree_ui/move_widget.ui \
    Program_UI/robort_tree_ui/waypoint.ui \
    Program_UI/robort_tree_ui/setio.ui \
    Program_UI/robort_tree_ui/waitset.ui \
    Program_UI/set_ui/paramwidget.ui \
    Program_UI/robort_tree_ui/code_intrupt.ui \
    Program_UI/robort_tree_ui/tree_stack.ui \
    Program_UI/fix_ui/fix.ui \
    Program_UI/KeyBoard_ui/keyboardnumdialog.ui

LIBS += -lpthread -lpcan -lm
LIBS += `pkg-config --libs --cflags libmodbus`

unix:!macx: LIBS += -L$$PWD/'lib/ver 2.0.5/acusb linux demo/64bit/dll/' -lCanCmd

INCLUDEPATH += $$PWD/'lib/ver 2.0.5/acusb linux demo/64bit/dll'
DEPENDPATH += $$PWD/'lib/ver 2.0.5/acusb linux demo/64bit/dll'

DISTFILES += \
    image/fontawesome-webfont.ttf \
    image/add-line_horizontal.png \
    image/add-line_vertical.png \
    image/array_down.png \
    image/checkbox_checked.png \
    image/checkbox_unchecked.png \
    image/error.png \
    image/Font Awesome Cheatsheet.png \
    image/info.png \
    image/question.png \
    image/radio_normal.png \
    image/radio_selected.png \
    image/sub-line_horizontal.png \
    image/sub-line_vertical.png \
    image/black.css \
    image/blue.css \
    image/gray.css \
    image/navy.css \
    image/favicon.ico \
    Eigen/CMakeLists.txt.user \
    Eigen/CMakeLists.txt
